_target_: sage.models.base.ConvNextCls
backbone:
  _target_: sage.models.model_zoo.convnext.build_convnext
  model_name: convnext-base
  num_classes: 3
criterion:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.0
name: ${model.backbone.model_name}