_target_: sage.models.base.ConvNext
backbone:
  _target_: sage.models.model_zoo.convnext.build_convnext
  model_name: convnext-base
  num_classes: 1
criterion:
  _target_: torch.nn.BCEWithLogitsLoss
name: ${model.backbone.model_name}-binary