_target_: sage.models.base.DensenetCls
backbone:
  _target_: sage.models.model_zoo.densenet.build_densenet
  model_depth: 121 # 169, 201, 264
  num_classes: 4
criterion:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.0
name: Densenet-cls