_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:run.dir}
filename: "{step}-valid_mae{epoch/valid_MeanAbsoluteError:.3f}"
monitor: epoch/valid_MeanAbsoluteError
mode: min
save_top_k: 1
save_last: True
# Is useful to set it to False when metric names contain / as this will result in extra folders
auto_insert_metric_name: False