_target_: pytorch_lightning.Trainer
max_epochs: 2
devices: 1
accelerator: gpu
gradient_clip_val: 1
log_every_n_steps: 50
accumulate_grad_batches: 4
fast_dev_run: True
limit_train_batches: 0.001
limit_val_batches: 0.01