# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
_target_: pytorch_lightning.Trainer
max_epochs: 300
devices: 1
accelerator: gpu
gradient_clip_val: 1
log_every_n_steps: 50
accumulate_grad_batches: 1
