scheduler:
  _target_: sage.trainer.scheduler.CosineAnnealingWarmupRestarts
  first_cycle_steps: 6000
  cycle_mult: 2
  max_lr: 4e-3
  min_lr: 1e-7
  warmup_steps: 4000
  gamma: 0.5
  last_epoch: -1
interval: step
frequency: 1
strict: False
