name: "ADNI Sweep"
description: "HPO for ADNI classification task"
method: bayes
metric:
  goal: maximize
  name: test_f1
parameters:
  optim:
    values: [ adamw , lion ]
  scheduler:
    values: [ exp_decay , cosine_anneal_warmup ]
  optim.lr:
    values: [ 5e-3 , 1e-3 , 1e-4 , 5e-5 ]
  model.backbone.model_depth:
    values: [ 10 , 18 , 34 ]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
run_cap: 50