method: bayes
metric:
  goal: maximize
  name: test_acc
parameters:
  optim:
    values: [ adamw , lion ]
  scheduler:
    values: [ exp_decay , cosine_anneal_warmup ]
  optim.lr:
    values: [ 5e-3 , 1e-3 , 1e-4 , 5e-5 ]