hydra:
  job:
    chdir: False  # keep hydra = 1.1 change directory behavior
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${logger.name}
  sweep:
    dir: ${hydra.run.dir}

defaults:
  - _self_
  - model: resnet_cls
  - dataset: adni
  - scheduler: exp_decay
  - optim: adamw
  - trainer: default
  - dataloader: default
  - metrics: cls
  - logger: wandb
  - module: default
  - callbacks/checkpoint: cls
  - callbacks/early_stop: cls
  - callbacks/lr_monitor: default
  - callbacks/richsummary: default
  - misc: default
