hydra:
  job:
    chdir: False  # keep hydra = 1.1 change directory behavior
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${logger.name}

defaults:
  - _self_
  - model: resnet
  - dataset: biobank_mask
  - scheduler: cosine_anneal_warmup
  - optim: lion
  - trainer: default
  - dataloader: default
  - metrics: reg
  - logger: wandb_mask
  - module: default
  - callbacks/checkpoint: reg
  - callbacks/early_stop: reg
  - callbacks/lr_monitor: default
  - callbacks/richsummary: default
  - misc: default

callbacks:
  manual_ckpt:
    _target_: sage.trainer.callbacks.AnchorCheckpoint
    multiplier: 1