hydra:
  job:
    chdir: False  # keep hydra = 1.1 change directory behavior
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${logger.name}
  sweep:
    dir: ${hydra.run.dir}

defaults:
  - _self_
  - model: convnext_cls
  - dataset: ppmi
  - scheduler: exp_decay
  - optim: adamw
  - trainer: default
  - dataloader: default
  - metrics: binary
  - logger: wandb
  - module: default
  - callbacks/checkpoint: binary
  - callbacks/early_stop: binary
  - callbacks/lr_monitor: default
  - callbacks/richsummary: default
  - misc: default
