_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:run.dir}
filename: "{step}-valid_f1-{epoch/valid_MulticlassF1Score:.3f}"
monitor: epoch/valid_MulticlassF1Score
mode: max
save_top_k: 1
save_last: True
# Is useful to set it to False when metric names contain / as this will result in extra folders
auto_insert_metric_name: False