# https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.LearningRateMonitor.html
_target_: pytorch_lightning.callbacks.LearningRateMonitor
logging_interval: step
log_momentum: False